project:
  type: website
  output-dir: docs

website:
  title: "Elijah Kates | Marketing Analytics Portfolio"
  description: "Portfolio showcasing marketing analytics, digital strategy, research, and data visualization projects by Elijah Kates."
  
  navbar:
    background: "#0D0D0D"
    
    left:
      - text: "Home"
        href: index.qmd

      - text: "Projects"
        href: projects.qmd

      - text: "Dashboard"
        href: dashboard.qmd

      - text: "Presentation"
        href: presentation.qmd

      - text: "Resume"
        href: resume.qmd

format:
  html:
    theme: [darkly, theme.scss]
    
    toc: true
    smooth-scroll: true
    
    page-layout: full
    
    include-in-header: includes/gtm-head.html
    include-before-body: includes/gtm-body.html